const PRICES = {
    "transfers": {
        "PARIS": {
            "PARIS": {
                "1": { "price": 60 },
                "2": { "price": 60 },
                "3": { "price": 60 },
                "4": { "price": 65 },
                "5": { "price": 65 },
                "6": { "price": 65 },
                "7": { "price": 70 },
                "8": { "price": 70 },
            },
            "DISNEY": {
            },
            "ORLY": {
                "1": { "price": 70 },
                "2": { "price": 70 },
                "3": { "price": 70 },
                "4": { "price": 75 },
                "5": { "price": 80 },
                "6": { "price": 85 },
                "7": { "price": 90 },
                "8": { "price": 95 },
            },
            "CDG": {
                "1": { "price": 75 },
                "2": { "price": 75 },
                "3": { "price": 75 },
                "4": { "price": 80 },
                "5": { "price": 85 },
                "6": { "price": 90 },
                "7": { "price": 95 },
                "8": { "price": 100 },
            },
            "BEAUVAIS": {
                "1": { "price": 150 },
                "2": { "price": 150 },
                "3": { "price": 150 },
                "4": { "price": 155 },
                "5": { "price": 160 },
                "6": { "price": 165 },
                "7": { "price": 170 },
                "8": { "price": 175 },   
            },
            "LA DEFENSE":{
                "1": { "price": 70 },
                "2": { "price": 70 },
                "3": { "price": 70 },
                "4": { "price": 75 },
                "5": { "price": 75 },
                "6": { "price": 80 },
                "7": { "price": 80 },
                "8": { "price": 85 },
            },
            "VERSAILLES":{
                "1": { "price": 80 },
                "2": { "price": 80 },
                "3": { "price": 80 },
                "4": { "price": 85 },
                "5": { "price": 90 },
                "6": { "price": 95 },
                "7": { "price": 100 },
                "8": { "price": 105 },
            },
            "GIVERNY": {
                "1": { "price": 160 },
                "2": { "price": 160 },
                "3": { "price": 160 },
                "4": { "price": 165 },
                "5": { "price": 170 },
                "6": { "price": 175 },
                "7": { "price": 180 },
                "8": { "price": 185 },
            },
            "DEAUVILLE": {
                "1": { "price": 550 },
                "2": { "price": 550 },
                "3": { "price": 550 },
                "4": { "price": 600 },
                "5": { "price": 600 },
                "6": { "price": 650 },
                "7": { "price": 700 },
                "8": { "price": 750 },
            },
            "PARIS TRAIN STATION": {
                "1": { "price": 60 },
                "2": { "price": 60 },
                "3": { "price": 60 },
                "4": { "price": 65 },
                "5": { "price": 65 },
                "6": { "price": 65 },
                "7": { "price": 70 },
                "8": { "price": 70 },
            },
            "FONTAINEBLEAU": {
                "1": { "price": 140 },
                "2": { "price": 140 },
                "3": { "price": 140 },
                "4": { "price": 145 },
                "5": { "price": 145 },
                "6": { "price": 150 },
                "7": { "price": 155 },
                "8": { "price": 155 },
            }
        },
        "DISNEY": {
            "PARIS": {
            },
            "ORLY": {
                "1": { "price": 80 },
                "2": { "price": 80 },
                "3": { "price": 80 },
                "4": { "price": 85 },
                "5": { "price": 90 },
                "6": { "price": 95 },
                "7": { "price": 100 },
                "8": { "price": 105 },
            },
            "CDG": {
                "1": { "price": 75 },
                "2": { "price": 75 },
                "3": { "price": 75 },
                "4": { "price": 80 },
                "5": { "price": 85 },
                "6": { "price": 90 },
                "7": { "price": 95 },
                "8": { "price": 100 },
            },
            "BEAUVAIS": {
                "1": { "price": 150 },
                "2": { "price": 150 },
                "3": { "price": 150 },
                "4": { "price": 150 },
                "5": { "price": 160 },
                "6": { "price": 170 },
                "7": { "price": 170 },
                "8": { "price": 170 },
            }
        },
        "ORLY": {
            "PARIS": {
                "1": { "price": 70 },
                "2": { "price": 70 },
                "3": { "price": 70 },
                "4": { "price": 75 },
                "5": { "price": 80 },
                "6": { "price": 85 },
                "7": { "price": 90 },
                "8": { "price": 95 },
            },
            "DISNEY": {
                "1": { "price": 80 },
                "2": { "price": 80 },
                "3": { "price": 80 },
                "4": { "price": 85 },
                "5": { "price": 90 },
                "6": { "price": 95 },
                "7": { "price": 100 },
                "8": { "price": 105 },
            },
            "LA DEFENSE": {
                "1": { "price": 75 },
                "2": { "price": 75 },
                "3": { "price": 75 },
                "4": { "price": 80 },
                "5": { "price": 85 },
                "6": { "price": 90 },
                "7": { "price": 95 },
                "8": { "price": 100 },
            },
            "CDG": {
                "1": { "price": 95 },
                "2": { "price": 95 },
                "3": { "price": 100 },
                "4": { "price": 105 },
                "5": { "price": 110 },
                "6": { "price": 115 },
                "7": { "price": 120 },
                "8": { "price": 125 },
            },
            "BEAUVAIS": {
                "1": { "price": 155 },
                "2": { "price": 155 },
                "3": { "price": 155 },
                "4": { "price": 160 },
                "5": { "price": 165 },
                "6": { "price": 170 },
                "7": { "price": 175 },
                "8": { "price": 180 },
            },
            "VERSAILLES": {
                "1": { "price": 75 },
                "2": { "price": 75 },
                "3": { "price": 75 },
                "4": { "price": 80 },
                "5": { "price": 85 },
                "6": { "price": 90 },
                "7": { "price": 95 },
                "8": { "price": 100 },
            },
            "PARIS TRAIN STATION": {
                "1": { "price": 70 },
                "2": { "price": 70 },
                "3": { "price": 70 },
                "4": { "price": 75 },
                "5": { "price": 80 },
                "6": { "price": 85 },
                "7": { "price": 90 },
                "8": { "price": 95 },
            }
        },
        "CDG": {
            "PARIS": {
                "1": { "price": 75 },
                "2": { "price": 75 },
                "3": { "price": 75 },
                "4": { "price": 80 },
                "5": { "price": 85 },
                "6": { "price": 90 },
                "7": { "price": 95 },
                "8": { "price": 100 },
            },
            "DISNEY": {
                "1": { "price": 75 },
                "2": { "price": 75 },
                "3": { "price": 75 },
                "4": { "price": 80 },
                "5": { "price": 85 },
                "6": { "price": 90 },
                "7": { "price": 95 },
                "8": { "price": 100 },
            },
            "ORLY": {
                "1": { "price": 85 },
                "2": { "price": 85 },
                "3": { "price": 85 },
                "4": { "price": 90 },
                "5": { "price": 95 },
                "6": { "price": 100 },
                "7": { "price": 105 },
                "8": { "price": 110 },
            },
            "BEAUVAIS": {
                "1": { "price": 125 },
                "2": { "price": 125 },
                "3": { "price": 125 },
                "4": { "price": 130 },
                "5": { "price": 135 },
                "6": { "price": 140 },
                "7": { "price": 145 },
                "8": { "price": 150 },
            },
            "LA DEFENSE": {
                "1": { "price": 90 },
                "2": { "price": 90 },
                "3": { "price": 90 },
                "4": { "price": 95 },
                "5": { "price": 100 },
                "6": { "price": 105 },
                "7": { "price": 110 },
                "8": { "price": 115 },
            },
            "GIVERNY": {
                "1": { "price": 400 },
                "2": { "price": 400 },
                "3": { "price": 400 },
                "4": { "price": 450 },
                "5": { "price": 500 },
                "6": { "price": 500 },
                "7": { "price": 500 },
                "8": { "price": 500 },
            },
            "DEAUVILLE": {
                "1": { "price": 550 },
                "2": { "price": 550 },
                "3": { "price": 550 },
                "4": { "price": 600 },
                "5": { "price": 600 },
                "6": { "price": 600 },
                "7": { "price": 650 },
                "8": { "price": 650 },
            },
            "PARIS TRAIN STATION": {
                "1": { "price": 75 },
                "2": { "price": 75 },
                "3": { "price": 75 },
                "4": { "price": 80 },
                "5": { "price": 85 },
                "6": { "price": 90 },
                "7": { "price": 95 },
                "8": { "price": 100 },
            }
        },
        "BEAUVAIS": {
            "PARIS": {
                "1": { "price": 150 },
                "2": { "price": 150 },
                "3": { "price": 150 },
                "4": { "price": 155 },
                "5": { "price": 160 },
                "6": { "price": 165 },
                "7": { "price": 170 },
                "8": { "price": 175 },   
            },
            "DISNEY": {
                "1": { "price": 150 },
                "2": { "price": 150 },
                "3": { "price": 150 },
                "4": { "price": 150 },
                "5": { "price": 160 },
                "6": { "price": 170 },
                "7": { "price": 170 },
                "8": { "price": 170 },   
            },
            "ORLY": {
                "1": { "price": 155 },
                "2": { "price": 155 },
                "3": { "price": 155 },
                "4": { "price": 155 },
                "5": { "price": 165 },
                "6": { "price": 165 },
                "7": { "price": 175 },
                "8": { "price": 175 }, 
            },
            "CDG": {
                "1": { "price": 125 },
                "2": { "price": 125 },
                "3": { "price": 125 },
                "4": { "price": 130 },
                "5": { "price": 135 },
                "6": { "price": 140 },
                "7": { "price": 145 },
                "8": { "price": 150 }, 
            },
            "LA DEFENSE": {
                "1": { "price": 130 },
                "2": { "price": 130 },
                "3": { "price": 130 },
                "4": { "price": 135 },
                "5": { "price": 140 },
                "6": { "price": 140 },
                "7": { "price": 145 },
                "8": { "price": 150 }, 
            },
            "VERSAILLES": {
                "1": { "price": 160 },
                "2": { "price": 160 },
                "3": { "price": 160 },
                "4": { "price": 165 },
                "5": { "price": 170 },
                "6": { "price": 175 },
                "7": { "price": 180 },
                "8": { "price": 185 },
            }, 
            "GIVERNY": {
                "1": { "price": 140 },
                "2": { "price": 140 },
                "3": { "price": 140 },
                "4": { "price": 145 },
                "5": { "price": 150 },
                "6": { "price": 155 },
                "7": { "price": 160 },
                "8": { "price": 165 },
            },
            "PARIS TRAIN STATION": {
                "1": { "price": 150 },
                "2": { "price": 150 },
                "3": { "price": 150 },
                "4": { "price": 155 },
                "5": { "price": 160 },
                "6": { "price": 165 },
                "7": { "price": 170 },
                "8": { "price": 175 },
            }    
        }
    },
    "extra_prices": {
        "night": {
            "0": 15,
            "1": 15,
            "2": 15,
            "3": 15,
            "4": 15,
            "5": 15,
            "6": 15,
            "7": 0,
            "8": 0,
            "9": 0,
            "10": 0,
            "11": 0,
            "12": 0,
            "13": 0,
            "14": 0,
            "15": 0,
            "16": 0,
            "17": 0,
            "18": 0,
            "19": 0,
            "20": 0,
            "21": 0,
            "22": 15,
            "23": 15
        }
    }
}
